import React from "react";
import Head from "next/head";
import Script from "next/script";

// layouts
import Header from "@layouts/Header";
import Footer from "@layouts/Footer";

// sections
import AboutSection from "@sections/AboutSection";

// components
import { Banner, Navigation } from "@components/common";

const AboutPage = () => (
  <>
    <Head>
      {/* Google Tag Manager */}
      <Script
        strategy="afterInteractive"
        type="text/partytown"
        dangerouslySetInnerHTML={{
          __html: `(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
            var f = d.getElementsByTagName(s)[0],
              j = d.createElement(s),
              dl = l != "dataLayer" ? "&l=" + l : "";
            j.async = true;
            j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
            f.parentNode.insertBefore(j, f);
          })(window, document, "script", "dataLayer", "GTM-WK9ZN93")`,
        }}></Script>
      {/* End Google Tag Manager */}
      <title>Dealer Marketing</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <body>
      <Header />
      <Navigation />
      <Banner
        url="/images/backgrounds/bg-oto.jpg"
        text="About Us"
        blurDataURL="/images/backgrounds/blur.jpg"
      />
      <AboutSection />
      <Footer />
    </body>
  </>
);

export default AboutPage;
