import React from "react";
import Head from "next/head";
import Header from "@layouts/Header";
import Footer from "@layouts/Footer";
import AboutSection from "@sections/AboutSection";
import { Banner, Navigation } from "@components/common";

const AboutPage = () => (
  <>
    <Head>
      <title>Dealer Marketing</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <Navigation />
    <Banner
      url="/images/backgrounds/bg-oto.jpg"
      text="About Us"
      blurDataURL="/images/backgrounds/blur.jpg"
    />
    <AboutSection />
    <Footer />
  </>
);

export default AboutPage;
