import Head from "next/head";
import React from "react";
import useSWR from "swr";
import Image from "next/image";
import { Blogs } from "@src/common-types/blog";
import { BLOG_URL } from "@src/constants/url";
import { getData } from "@src/helpers/fetchApi";
import { useRouter } from "next/router";
import Banner from "@src/components/common/Banner/Banner";
import Footer from "@src/components/common/Footer/Footer";
import Header from "@src/components/common/Header/Header";
import Navigation from "@src/components/common/Navigation/Navigation";
import style from "../styles/base/common.module.css";
import Text from "@src/components/common/Text/Text";

const BlogDetail = () => {
  const router = useRouter();
  const { slug } = router.query;
  const { data } = useSWR(BLOG_URL + "?slug=" + slug, getData<Blogs[]>);
  const {
    title = "",
    expertId = "",
    createDate = "",
    description = "",
    image = { url: "/images/past-present-future.avif", alt: "" },
  } = data ? data[0] : {};

  console.log("data", data);

  return (
    <div>
      <Head>
        <title>Dealer Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>

      <Header />
      <Navigation />
      <Banner url={image.url} text="" />
      <div className="container">
        <div className={style["style-info"]}>
          <div className={style["style-card"]}>
            <div className={style["style-title"]}>
              <Text size="large-dark" text={title} />
            </div>
            <hr />
            <div className={style["style-author"]}>
              <figure>
                <Image
                  src={image.url}
                  alt={image.alt}
                  className={style["style-image"]}
                  width={60}
                  height={60}
                />
              </figure>
              <div className={style["style-funeral"]}>
                <p>
                  by <span>{expertId}</span>
                </p>
                <p>{createDate}</p>
              </div>
            </div>
          </div>
          <hr />
          <div className={style["style-info-regular"]}>
            <Text size="regular" text={description} />
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default BlogDetail;
