import React from "react";
import Header from "@src/components/common/Header/Header";
import Navigation from "@src/components/common/Navigation/Navigation";
import ExpertList from "@src/components/ExpertList/ExpertList";
import style from "../styles/base/common.module.css";
import Text from "@src/components/common/Text/Text";
import Head from "next/head";
import Footer from "@src/components/common/Footer/Footer";

const OurExpertPage = () => {
  return (
    <div className={style.ourExpert}>
      <Head>
        <title>Dealer Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>

      <Header />
      <div className={style.navigation}>
        <Navigation />
      </div>
      <div className={style.description}>
        <h2 className={style.heading}>The DMM Expert Panel</h2>
        <Text
          size="regular"
          text="Our Expert Panel consists of thirty automotive industry experts who share their knowledge and experience to help keep dealers informed on various topics such as Business Development, Dealership Business, Fixed Ops, Internet Marketing, Advertising, AI, Tech Solutions, Industry & Consumer Research, and more. With a combined LinkedIn following of 113,000+ followers, as an automotive industry professional or vendor, you are guaranteed to learn something new."
        />
      </div>
      <div className={style.expert}>
        <ExpertList />
      </div>
      <Footer />
    </div>
  );
};

export default OurExpertPage;
