import Head from "next/head";
import type { NextPage } from "next";
import { Banner, Navigation } from "@components/common";
import Header from "@sections/Header";
import Footer from "@sections/Footer";
import MainSection from "@sections/MainSection";
import axios from "axios";
import { BLOG_URL } from "@constants/url";
import { Blog } from "@common-types/blog";
import { useContext, useEffect } from "react";
import { DataContext } from "@context/DataContext";

interface HomeProps {
  blogs: Blog[];
}

export const getStaticProps = async () => {
  const res = await axios.get(BLOG_URL);

  return {
    props: {
      blogs: res.data,
    },
  };
};

const Home: NextPage<HomeProps> = ({ blogs }) => {
  const { setBlogs } = useContext(DataContext);
  useEffect(() => {
    setBlogs(blogs);
  }, [blogs]);

  return (
    <>
      <Head>
        <title>Dealer Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>

      <main>
        <Header />
        <Navigation />
        <Banner
          url="/images/backgrounds/home-page.png"
          text="Expert Automotive Knowledge at Your Fingertips"
        />
        <MainSection />
      </main>
      <Footer />
    </>
  );
};

export default Home;
