import type { NextPage } from "next";
import { useContext, useEffect } from "react";
import axios from "axios";
import Head from "next/head";

// components
import { Banner, Navigation } from "@components/common";

// constants
import { BLOG_URL } from "@constants/url";

// common-types
import { Blog } from "@common-types/blog";

// layouts
import Footer from "@layouts/Footer";
import Header from "@layouts/Header";

import { DataContext } from "@context/DataContext";
import MainSection from "@sections/MainSection";

interface HomeProps {
  blogs: Blog[];
  errorCode: string;
}

export const getStaticProps = async () => {
  try {
    const res = await axios.get(BLOG_URL);
    const blogs = res.data;
    return {
      props: {
        blogs: blogs,
        errorCode: false,
      },
    };
  } catch (errorCode) {
    return {
      props: {
        blogs: [],
        errorCode: errorCode,
      },
    };
  }
};

const Home: NextPage<HomeProps> = ({ blogs, errorCode }) => {
  const { setBlogs, setErrorCode } = useContext(DataContext);
  useEffect(() => {
    setBlogs(blogs);
    setErrorCode(errorCode);
  }, []);

  return (
    <>
      <Head>
        <title>Dealer Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Navigation />
        <Banner
          url="/images/backgrounds/home-page.png"
          blurDataURL="/images/backgrounds/blur.jpg"
          text="Expert Automotive Knowledge at Your Fingertips"
        />
        <MainSection />
      </main>
      <Footer />
    </>
  );
};

export default Home;
