import useSWR from "swr";
import React from "react";
import { useRouter } from "next/router";
import { EXPERT_URL } from "@src/constants/url";
import { getData } from "@src/helpers/fetchApi";
import { Experts } from "@src/common-types/expert";
import Head from "next/head";
import Header from "@src/components/common/Header/Header";
import Navigation from "@src/components/common/Navigation/Navigation";
import Banner from "@src/components/common/Banner/Banner";
import Footer from "@src/components/common/Footer/Footer";
import style from "../../styles/base/common.module.css";
import Image from "next/image";
import Text from "@src/components/common/Text/Text";

const OurExpert = () => {
  const router = useRouter();
  const { slug } = router.query;
  const { data } = useSWR(EXPERT_URL + "?slug=" + slug, getData<Experts[]>);
  const {
    name = "",
    info = "",
    description = "",
    image = { url: "/images/avatar/matt-childers.png", alt: "" },
  } = data ? data[0] : {};
  console.log("data", data);

  return (
    <div>
      <Head>
        <title>Dealer Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navigation />
      <Banner url="/images/backgrounds/bg-oto.jpg" text="" />
      <div className={style["container-expert"]}>
        <figure className={style["style-layout-image"]}>
          <Image
            src={image.url}
            alt={image.alt}
            className={style["style-image"]}
            width={130}
            height={130}
          />
        </figure>
        <div className={style["style-info"]}>
          <h2 className={style["style-name"]}>{name}</h2>
          <p className={style["style-content"]}>{info}</p>
          <Text size="regular" text={description} />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default OurExpert;
