export const IMAGE = {
  whiteLogo: '/images/logos/white-logo.svg',
  blackLogo: '/images/logos/black-logo.svg',
  blackShoes: '/images/products/black-shoes.png',
  blueShoes: '/images/products/blue-shoes.png',
  grayShoes: '/images/products/gray-shoes.png',
  greenShoes: '/images/products/green-shoes.png',
  whiteShoes: '/images/products/white-shoes.png',
  blackWhiteShoes: '/images/products/black-white-shoes.png',
  altLogo: 'This is logo sopa',
  altBlackShoes: 'This is black shoes',
  altBlueShoes: 'This is blue shoes',
  altGrayShoes: 'This is gray shoes',
  altGreenShoes: 'This is green shoes',
  altWhiteShoes: 'This is white shoes',
  altBlackWhiteShoes: 'This is back white shoes',
};
